name: my_portfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management and Navigation
  get: ^4.6.6
  provider: ^6.1.1

  # UI Components
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0
  
  # Network and Data
  url_launcher: ^6.2.5
  http: ^1.2.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  
  # Styling and Utils
  google_fonts: ^6.1.0
  visibility_detector: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/1.jpg
    - assets/2.jpg
    - assets/poerfolioimg.jpg
    - assets/dp.jpg

